dist: xenial
language: node_js
node_js:
  - "6" #current LTS
cache:
  yarn: true
install:
  - yarn
script:
  - yarn install
  - yarn test
  - yarn build
deploy:
  provider: pages
  local_dir: react-app/build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages


